### ISSUE TITLE
[TODO] List of sandwich ingredients

### ISSUE THREAD

**Issue by AaronLieb** [hellokev/Sandwich-Project#5]
We need a comprehensive list of as many sandwich ingredients as possible. 

Requirements:
1. Create categories of sandwich ingredients
2. Collect and organize ingredients into these categories

If you'd like to start working on this, assign yourself to the issue and get started!

Feel free to shoot me any questions

**Comment by DavidJSolano** [comment]
**Bread:** (Bottom Priority 0, Top Priority 7)
White bread
Whole wheat bread
Sourdough bread
Rye bread
Baguette
Ciabatta
Focaccia
Pita bread
Naan
Croissant
Brioche
Gluten-free bread
**Meat:** (Priority 1)
Ham
Turkey
Roast beef
Chicken
Bacon
Salami
Pepperoni
Pastrami
Corned beef
Prosciutto
Meatballs
Pulled pork
Tuna salad
Chicken salad
Egg salad
**Cheese:** (Priority 2)
Cheddar
Swiss
American
Pepper jack
Provolone
Mozzarella
Feta
Gouda
Brie
Blue cheese
Cream cheese
**Vegetables:** (Priority 3)
Lettuce
Tomato
Cucumber
Onion
Avocado
Spinach
Kale
Arugula
Bell pepper
Carrot
Radish
Sprouts
Pickles
Olives
Roasted red peppers
**Condiments:** (Priority 4)
Mayonnaise
Mustard
Ketchup
BBQ sauce
Ranch dressing
Honey mustard
Caesar dressing
Sriracha
Pesto
Hummus
Guacamole
Aioli
Horseradish
**Spreads:** ( Priority 5)
Peanut butter
Almond butter
Nutella
Jelly
Jam
Honey
Apple butter
Cream cheese
**Other:** (Priority 6)
Eggs
Bacon bits
Croutons
Nuts
Sun-dried tomatoes
Salsa
Coleslaw
Roasted garlic
Artichoke hearts
Roasted eggplant
Falafel balls
Seitan
